version: '3'

volumes:
  election_data:
  log_data:

services:
  db:
    image: mysql:5.7
    volumes:
      - election_data:/var/lib/mysql
      - log_data:/var/log
    environment:
      - MYSQL_DATABASE_NAME=election
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - "33066:3306"
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci,  --log_error_verbosity=1]
    healthcheck:
      test: "mysqladmin -u root -prootpassword ping"
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      - custom
  
  election:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./Election:/app
    environment:
      - DB_URL=db:3306
      - DB_NAME=election
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - server_build_type=Local
      - BlockChainURL=blockchain
      - BlockChainNumber=3
      - BlockChainPort=5000
    ports:
      - "5000:5000"
    links:
      - db
      - blockchain1
      - blockchain2
      - blockchain3
    sysctls:
      - net.core.somaxconn=4096
    networks:
      - custom
    depends_on:
      - db
    tty: true

  blockchain1:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./BlockChain:/app
    ports:
      - "5001:5000"
    environment:
      - BlockChainURL1=http://blockchain2:5000
      - BlockChainURL2=http://blockchain3:5000
    networks:
      - custom
    external_links:
      - blockchain1:blockchain2
      - blockchain2:blockchain3
    sysctls:
      - net.core.somaxconn=4096
    #tty: true
    command: python3 manager.py runserver -p 5000 -h 0.0.0.0

  blockchain2:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./BlockChain:/app
    ports:
      - "5002:5000"
    environment:
      - BlockChainURL1=http://blockchain1:5000
      - BlockChainURL2=http://blockchain3:5000
    networks:
      - custom
    external_links:
      - blockchain1:blockchain1
      - blockchain3:blockchain3
    sysctls:
      - net.core.somaxconn=4096
    #tty: true
    command: python3 manager.py runserver -p 5000 -h 0.0.0.0

  blockchain3:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./BlockChain:/app
    ports:
      - "5003:5000"
    environment:
      - BlockChainURL1=http://blockchain1:5000
      - BlockChainURL2=http://blockchain2:5000
    networks:
      - custom
    external_links:
      - blockchain1:blockchain1
      - blockchain2:blockchain2
    sysctls:
      - net.core.somaxconn=4096
    #tty: true
    command: python3 manager.py runserver -p 5000 -h 0.0.0.0


networks:
  custom:
    external: true