version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - "33066:3306"
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci,  --log_error_verbosity=1]
    healthcheck:
      test: "mysqladmin -u root -prootpassword ping"
      interval: 3s
      timeout: 1s
      retries: 10
  
  election:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./Election:/app
    environment:
      - DB_URL=db
      - DB_NAME=election
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    ports:
      - "5000:5000"
    links:
      - db
    sysctls:
      - net.core.somaxconn=4096
    depends_on:
      - db
    tty: true

